name: CI

on:
  push:
    branches: [ 'main' ]
    tags-ignore: [v*]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 11, 17 ]

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Build on Java ${{ matrix.java }}
        run: ./gradlew build --no-daemon

      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.47.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - run: ktlint .
